#!/bin/bash

replica_host_names=(ec2-54-85-32-37.compute-1.amazonaws.com
                     ec2-54-193-70-31.us-west-1.compute.amazonaws.com
                     ec2-52-38-67-246.us-west-2.compute.amazonaws.com
                     ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
                     ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
                     ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
                     ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
                     ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
                     ec2-54-233-185-94.sa-east-1.compute.amazonaws.com
		     )
while getopts p:o:n:u:i: args
do
	case $args in
		p)
		   #port=$OPTARG
		   #echo $port
		   ;;
		o)
		   #orignalServer=$OPTARG
		   #echo $orignalServer	
		   ;;
		n)
		   #name=$OPTARG
		   #echo $name
		   ;;
		u)
		   username=$OPTARG 
		   echo $username
		   ;;
		i)
		   keyfile=$OPTARG
		   #keyfile=$OPTARG
		   #echo $keyfile
		   ;;
		?)
		   echo "usage: ./deployCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
		   exit 1
		   ;;
 	esac
done
shift $((OPTIND-1))

echo "===================================================================================="
echo "Replica Server Deploy is starting now !"
echo "===================================================================================="

for host in "${replica_host_names[@]}"
do
	echo "Deploying host: " $host
        echo $keyfile 
	echo $username
	ssh -i $keyfile $username@$host 'mkdir ~/scripts/'
	echo "command executed successfully -------> [~\/scripts\/] "
        
	scp -i $keyfile baseUtility.py $username@$host:~/scripts/
	echo "command executed successfully ----------> [baseUtility.py in ~/scripts/]"
        
	scp -i $keyfile performanceMeasureServer.py $username@$host:~/scripts/
  echo "command executed successfully --------> [performanceMeasureServer.py in ~/scripts/]"
  scp -i $keyfile httpserver $username@$host:~/scripts/
  echo "command executed successfully --------> [httpserver in ~/scripts/]"
  
  scp -i $keyfile httpserver.py $username@$host:~/scripts/
	echo "command executed successfully --------> [httpserver.py in ~/scripts/]"

done

echo "===================================================================================="
echo "Replica Server Deploy successfully!"
echo "************************************************************************************"
echo "DNS Server Deploy is starting!"
echo "===================================================================================="

dnsserver=cs5700cdnproject.ccs.neu.edu

echo "Deploy DNS server script to DNS Server " $dnsserver

ssh -i $keyfile $username@$dnsserver 'mkdir ~/scripts/'
echo "command executed successfully! -------> [~/scripts/]"

scp -i $keyfile dnsserver.py $username@$dnsserver:~/scripts/
echo "command executed successfully! --------> [dnsserver.py in ~/scripts/]"

scp -i $keyfile dnsserver $username@$host:~/scripts/
echo "command executed successfully --------> [dnsserver in ~/scripts/]"

scp -i $keyfile DelayProcess.py $username@$dnsserver:~/scripts/
echo "command executed successfully! ----------> [DeplayProcess.py in ~/scripts/]"

echo "==================================================================================="
echo "DNS server Deployed successfully"
echo "==================================================================================="
 


     
