default:
	sh -c "chmod +x ./httpserver.py"
	sh -c "chmod +x ./dnsserver.py"
	sh -c "chmod +x ./httpserver"
	sh -c "chmod +x ./dnsserver"
	sh -c "chmod +x ./deployCDN"
	sh -c "chmod +x ./runCDN"
	sh -c "chmod +x ./stopCDN"
