#!/bin/bash

replica_host_names=(ec2-54-85-32-37.compute-1.amazonaws.com
                     ec2-54-193-70-31.us-west-1.compute.amazonaws.com
                     ec2-52-38-67-246.us-west-2.compute.amazonaws.com
                     ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
                     ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
                     ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
                     ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
                     ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
                     ec2-54-233-185-94.sa-east-1.compute.amazonaws.com
		    )
while getopts p:o:n:u:i: args
do
	case $args in
		p) port=$OPTARG
		   echo $port
		   ;;
		o) orignalServer=$OPTARG
		   echo $orignalServer	
		   ;;
		n) name=$OPTARG #it should be cdn specified name ----> cs5700cdn.example.com
		   echo $name
		   ;;
		u) username=$OPTARG #replica username 
		   echo $username
		   ;;
		i) keyfile=$OPTARG # replica private key file
		   echo $keyfile
		   ;;
		?)
		   echo "usage: ./runCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
		   exit 1
		   ;;
 	         esac
done

echo "===================================================================================="
echo "Replica Server is start running now !"
echo "===================================================================================="

for host in "${replica_host_names[@]}"
do
	echo "Start running:  host -------->" $host
        
	ssh -i $keyfile -n -f $username@$host "sh -c 'cd ~/scripts/; nohup python performanceMeasureServer.py  > /dev/null 2>&1 &'"
	ssh -i $keyfile -n -f $username@$host "sh -c 'cd ~/scripts/; nohup python httpserver.py -p $port -o $orignalServer  > /dev/null 2>&1 &'"
done

echo "===================================================================================="
echo "Replica Server Running successfully!"
echo "************************************************************************************"
echo "DNS Server is staring running!"
echo "===================================================================================="

dnsserver=cs5700cdnproject.ccs.neu.edu

echo "Running DNS Server" $dnsserver
echo "----------------------------------"
echo "port ----->" $port
echo "name ------>" $name
echo "----------------------------------"
#ssh -i $keyfile -n -f $username@$dnsserver "sh -c 'cd ~/scripts/; nohup python dnsserver.py -p $port -n $name  > /dev/null 2>&1 &'"
ssh -i $keyfile -n -f $username@$dnsserver "sh -c 'cd ~/scripts/; nohup ./dnsserver -p $port -n $name > /dev/null 2>&1 &'"
echo "==================================================================================="
echo "DNS server running successfully"
echo "==================================================================================="
 


    
