#!/bin/bash

replica_host_names=(ec2-54-85-32-37.compute-1.amazonaws.com
                    ec2-54-193-70-31.us-west-1.compute.amazonaws.com
                    ec2-52-38-67-246.us-west-2.compute.amazonaws.com
                    ec2-52-51-20-200.eu-west-1.compute.amazonaws.com
                    ec2-52-29-65-165.eu-central-1.compute.amazonaws.com
                    ec2-52-196-70-227.ap-northeast-1.compute.amazonaws.com
                    ec2-54-169-117-213.ap-southeast-1.compute.amazonaws.com
                    ec2-52-63-206-143.ap-southeast-2.compute.amazonaws.com
                    ec2-54-233-185-94.sa-east-1.compute.amazonaws.com
		     )
while getopts p:o:n:u:i: args
do
	case $args in
		p) #port=$OPTARG
		   #echo $port
		   ;;
		o) #orignalServer=$OPTARG
		   #echo $orignalServer	
		   ;;
		n) #name=$OPTARG
		   #echo $name
		   ;;
		u) username=$OPTARG 
		   echo $username
		   ;;
		i) keyfile=$OPTARG
		   echo $keyfile
		   ;;
		?)
		   echo "usage: ./stopCDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>"
		   exit 1
		   ;;
 	         esac
done

echo "===================================================================================="
echo "Replica Server Deploy is stopping now !"
echo "===================================================================================="

for host in "${replica_host_names[@]}"
do
	echo "Stop host -------->" $host
	ssh -i $keyfile $username@$host 'killall python'
done

echo "===================================================================================="
echo "Replica Server Stop successfully!"
echo "************************************************************************************"
echo "DNS Server Deploy is stopping!"
echo "===================================================================================="

dnsserver=cs5700cdnproject.ccs.neu.edu

echo "Stopping DNS Server" $dnsserver
ssh -i $keyfile $username@$dnsserver 'killall python'

echo "==================================================================================="
echo "DNS server stopped successfully"
echo "==================================================================================="
 


     
